# Meta

title:         "Baobo.css"
description:   "Baobo CSS framework"

# Build

markdown:      kramdown
permalink:     pretty
url:           https://baobohealth.github.io/baobo.css
exclude:       ['icons', 'node_modules', 'templates', '.babelrc', 'baobo-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']

# Variables

documentation: "/documentation/overview/start/"
download:      https://github.com/BaoboHealth/baobo.css/archive/0.0.1.zip
github:        https://github.com/BaoboHealth/baobo.css
version:       0.0.1
